export const currecyvalue = [
  {
    value: "European euro",
    label: "European euro",
  },
  {
    value: "Albanian lek",
    label: "Albanian lek",
  },
  {
    value: "Algerian dinar",
    label: "Algerian dinar",
  },
  {
    value: "United States dollar",
    label: "United States dollar",
  },
  {
    value: "Angolan kwanza",
    label: "Angolan kwanza",
  },
  {
    value: "East Caribbean dollar",
    label: "East Caribbean dollar",
  },
  {
    value: "Argentine peso",
    label: "Argentine peso",
  },
  {
    value: "Armenian dram",
    label: "Armenian dram",
  },
  {
    value: "Aruban florin",
    label: "Aruban florin",
  },
  {
    value: "Saint Helena pound",
    label: "Saint Helena pound",
  },
  {
    value: "Australian dollar",
    label: "Australian dollar",
  },
  {
    value: "Azerbaijan manat",
    label: "Azerbaijan manat",
  },
  {
    value: "Bahamian dollar",
    label: "Bahamian dollar",
  },
  {
    value: "Bahraini dinar",
    label: "Bahraini dinar",
  },
  {
    value: "Bangladeshi taka",
    label: "Bangladeshi taka",
  },
  {
    value: "Barbadian dollar",
    label: "Barbadian dollar",
  },
  {
    value: "Belarusian ruble",
    label: "Belarusian ruble",
  },
  {
    value: "Belize dollar",
    label: "Belize dollar",
  },
  {
    value: "West African CFA franc",
    label: "West African CFA franc",
  },
  {
    value: "Bermudian dollar",
    label: "Bermudian dollar",
  },
  {
    value: "Bhutanese ngultrum",
    label: "Bhutanese ngultrum",
  },
  {
    value: "Bolivian boliviano",
    label: "Bolivian boliviano",
  },
  {
    value: "Bosnia and Herzegovina convertible mark",
    label: "Bosnia and Herzegovina convertible mark",
  },
  { value: "Brazilian real", label: "Brazilian real" },
  { value: "Brunei dollar", label: "Brunei dollar" },
  { value: "Bulgarian lev", label: "Bulgarian lev" },
  { value: "West African CFA franc", label: "West African CFA franc" },
  { value: "Cabo Verdean escudo", label: "Cabo Verdean escudo" },
  { value: "Cambodian riel", label: "Cambodian riel" },
  { value: "Central African CFA franc", label: "Central African CFA franc" },
  { value: "Canadian dollar", label: "Canadian dollar" },
  { value: "Cayman Islands dollar", label: "Cayman Islands dollar" },
  { value: "Central African CFA franc", label: "Central African CFA franc" },
  { value: "New Zealand dollar", label: "New Zealand dollar" },
  { value: "Chilean peso", label: "Chilean peso" },
  { value: "Chinese Yuan Renminbi", label: "Chinese Yuan Renminbi" },
  { value: "Colombian peso", label: "Colombian peso" },
  { value: "Comorian franc", label: "Comorian franc" },
  { value: "Congolese franc", label: "Congolese franc" },
  { value: "Central African CFA franc", label: "Central African CFA franc" },
  { value: "Cook Islands dollar", label: "Cook Islands dollar" },
  { value: "Costa Rican colon", label: "Costa Rican colon" },
  { value: "West African CFA franc", label: "West African CFA franc" },
  { value: "Croatian kuna", label: "Croatian kuna" },
  { value: "Cuban peso", label: "Cuban peso" },
  { value: "Netherlands Antillean guilder", label: "Netherlands Antillean guilder" },
  { value: "Czech koruna", label: "Czech koruna" },
  { value: "Danish krone", label: "Danish krone" },
  { value: "Djiboutian franc", label: "Djiboutian franc" },
  { value: "Dominican peso", label: "Dominican peso" },
  { value: "Egyptian pound", label: "Egyptian pound" },
  { value: "Eritrean nakfa", label: "Eritrean nakfa" },
  { value: "Swazi lilangeni", label: "Swazi lilangeni" },
  { value: "Ethiopian birr", label: "Ethiopian birr" },
  { value: "Falkland Islands pound", label: "Falkland Islands pound" },
  { value: "Faroese krona", label: "Faroese krona" },
  { value: "Fijian dollar", label: "Fijian dollar" },
  { value: "CFP franc", label: "CFP franc" },
  { value: "Gambian dalasi", label: "Gambian dalasi" },
  { value: "Georgian lari", label: "Georgian lari" },
  { value: "Ghanaian cedi", label: "Ghanaian cedi" },
  { value: "Gibraltar pound", label: "Gibraltar pound" },
  { value: "Danish krone", label: "Danish krone" },
  { value: "Guatemalan quetzal", label: "Guatemalan quetzal" },
  { value: "Guernsey Pound", label: "Guernsey Pound" },
  { value: "Guinean franc", label: "Guinean franc" },
  { value: "Guyanese dollar", label: "Guyanese dollar" },
  { value: "Haitian gourde", label: "Haitian gourde" },
  { value: "Honduran lempira", label: "Honduran lempira" },
  { value: "Hong Kong dollar", label: "Hong Kong dollar" },
  { value: "Hungarian forint", label: "Hungarian forint" },
  { value: "Icelandic krona", label: "Icelandic krona" },
  { value: "Indian rupee", label: "Indian rupee" },
  { value: "Indonesian rupiah", label: "Indonesian rupiah" },
  { value: "SDR (Special Drawing Right)", label: "SDR (Special Drawing Right)" },
  { value: "Iranian rial", label: "Iranian rial" },
  { value: "Iraqi dinar", label: "Iraqi dinar" },
  { value: "Manx pound", label: "Manx pound" },
  { value: "Israeli new shekel", label: "Israeli new shekel" },
  { value: "Jamaican dollar", label: "Jamaican dollar" },
  { value: "Japanese yen", label: "Japanese yen" },
  { value: "Jersey pound", label: "Jersey pound" },
  { value: "Jordanian dinar", label: "Jordanian dinar" },
  { value: "Kazakhstani tenge", label: "Kazakhstani tenge" },
  { value: "Kenyan shilling", label: "Kenyan shilling" },
  { value: "Kuwaiti dinar", label: "Kuwaiti dinar" },
  { value: "Kyrgyzstani som", label: "Kyrgyzstani som" },
  { value: "Lao kip", label: "Lao kip" },
  { value: "Lebanese pound", label: "Lebanese pound" },
  { value: "Lesotho loti", label: "Lesotho loti" },
  { value: "Liberian dollar", label: "Liberian dollar" },
  { value: "Libyan dinar", label: "Libyan dinar" },
  { value: "Swiss franc", label: "Swiss franc" },
  { value: "Macanese pataca", label: "Macanese pataca" },
  { value: "Malagasy ariary", label: "Malagasy ariary" },
  { value: "Malawian kwacha", label: "Malawian kwacha" },
  { value: "Malaysian ringgit", label: "Malaysian ringgit" },
  { value: "Maldivian rufiyaa", label: "Maldivian rufiyaa" },
  { value: "West African CFA franc", label: "West African CFA franc" },
  { value: "Mauritanian ouguiya", label: "Mauritanian ouguiya" },
  { value: "Mauritian rupee", label: "Mauritian rupee" },
  { value: "Mexican peso", label: "Mexican peso" },
  { value: "Moldovan leu", label: "Moldovan leu" },
  { value: "Mongolian tugrik", label: "Mongolian tugrik" },
  { value: "East Caribbean dollar", label: "East Caribbean dollar" },
  { value: "Moroccan dirham", label: "Moroccan dirham" },
  { value: "Moroccan dirham", label: "Moroccan dirham" },
  { value: "Mozambican metical", label: "Mozambican metical" },
  { value: "Myanmar kyat", label: "Myanmar kyat" },
  { value: "Nepalese rupee", label: "Nepalese rupee" },
  { value: "Nicaraguan cordoba", label: "Nicaraguan cordoba" },
  { value: "Nigerian naira", label: "Nigerian naira" },
  { value: "North Korean won", label: "North Korean won" },
  { value: "Macedonian denar", label: "Macedonian denar" },
  { value: "Norwegian krone", label: "Norwegian krone" },
  { value: "dOmani rial", label: "Omani riald" },
  { value: "Pakistani rupee", label: "Pakistani rupee" },
  { value: "Israeli new shekel", label: "Israeli new shekel" },
  { value: "Papua New Guinean kina", label: "Papua New Guinean kina" },
  { value: "Paraguayan guarani", label: "Paraguayan guarani" },
  { value: "Paraguayan guarani", label: "Paraguayan guarani" },
  { value: "Peruvian sol", label: "Peruvian sol" },
  { value: "Philippine peso", label: "Philippine peso" },
  { value: "Qatari riyal", label: "Qatari riyal" },
  { value: "Romanian leu", label: "Romanian leu" },
  { value: "Russian ruble", label: "Russian ruble" },
  { value: "Rwandan franc", label: "Rwandan franc" },
  { value: "Saint Helena pound", label: "Saint Helena pound" },
  { value: "East Caribbean dollar", label: "East Caribbean dollar" },
  { value: "Samoan tala", label: "Samoan tala" },
  { value: "European euro", label: "European euro" },
  { value: "Sao Tome and Principe dobra", label: "Sao Tome and Principe dobra" },
  { value: "Saudi Arabian riyal", label: "Saudi Arabian riyal" },
  { value: "West African CFA franc", label: "West African CFA franc" },
  { value: "Serbian dinar", label: "Serbian dinar" },
  { value: "Seychellois rupee", label: "Seychellois rupee" },
  { value: "Sierra Leonean leone", label: "Sierra Leonean leone" },
  { value: "Netherlands Antillean guilder", label: "Netherlands Antillean guilder" },
  { value: "Solomon Islands dollar", label: "Solomon Islands dollar" },
  { value: "Somali shilling", label: "Somali shilling" },
  { value: "South African rand", label: "South African rand" },
  { value: "Pound sterling", label: "Pound sterling" },
  { value: "South Korean won", label: "South Korean won" },
  { value: "South Sudanese pound", label: "South Sudanese pound" },
  { value: "Sri Lankan rupee", label: "Sri Lankan rupee" },
  { value: "Sri Lankan rupee", label: "Sri Lankan rupee" },
  { value: "Sri Lankan rupee", label: "Sri Lankan rupee" },
  { value: "Surinamese dollar", label: "Surinamese dollar" },
  { value: "Norwegian krone", label: "Norwegian krone" },
  { value: "Swedish krona", label: "Swedish krona" },
  { value: "Swedish krona", label: "Swedish krona" },
  { value: "Syrian pound", label: "Syrian pound" },
  { value: "New Taiwan dollar", label: "New Taiwan dollar" },
  { value: "Tajikistani somoni", label: "Tajikistani somoni" },
  { value: "Tanzanian shilling", label: "Tanzanian shilling" },
  { value: "Thai baht", label: "Thai baht" },
  { value: "Tongan pa�anga", label: "Tongan pa�anga" },
  { value: "Trinidad and Tobago dollar", label: "Trinidad and Tobago dollar" },
  { value: "Pound sterling", label: "Pound sterling" },
  { value: "Tunisian dinar", label: "Tunisian dinar" },
  { value: "Turkish lira", label: "Turkish lira" },
  { value: "Turkmen manat", label: "Turkmen manat" },
  { value: "Ugandan shilling", label: "Ugandan shilling" },
  { value: "Ukrainian hryvnia", label: "Ukrainian hryvnia" },
  { value: "UAE dirham", label: "UAE dirham" },
  { value: "Pound sterling", label: "Pound sterling" },
  { value: "Uruguayan peso", label: "Uruguayan peso" },
  { value: "Uzbekistani som", label: "Uzbekistani som" },
  { value: "Vanuatu vatu", label: "Vanuatu vatu" },
  { value: "Venezuelan bolivar", label: "Venezuelan bolivar" },
  { value: "Vietnamese dong", label: "Vietnamese dong" },
  { value: "Yemeni rial", label: "Yemeni rial" },
  { value: "Zambian kwacha", label: "Zambian kwacha" },
];

export const options = [
  { value: "environment1", label: "Environment 1" },
  { value: "environment2", label: "Environment 2" },
  { value: "environment3", label: "Environment 3" },
];

export const frunitoption = [
  { value: "FR Unit 1", label: "FR Unit 1" },
  { value: "FR Unit 2", label: "FR Unit 2" },
  { value: "FR Unit 3", label: "FR Unit 3" },
];
export const Models = [
  { value: "PBS", label: "PBS" },
  {
    value: "Failure Rate Prediction",
    label: "Failure Rate Prediction",
  },
  {
    value: "MTTR Prediction",
    label: "MTTR Prediction",
  },
  {
    value: "FMECA",
    label: "FMECA",
  },
  {
    value: "RBD",
    label: "RBD",
  },
  {
    value: "FTA",
    label: "FTA",
  },
  {
    value: "PM MRA",
    label: "PM MRA",
  },
  {
    value: "Spare Part Analysis",
    label: "Spare Part Analysis",
  },
];
